import { Activity, Calendar } from 'lucide-react';
import {
    PieChart, Pie, Cell, ResponsiveContainer,
    XAxis, YAxis, CartesianGrid, Tooltip, Legend, AreaChart, Area
} from 'recharts';

// Mocked data from the SQL Cubes generated by -fact
const stats = [
    { name: 'Total Revenue', value: '€425,000', change: '+12.5%', trend: 'up' },
    { name: 'Operating Expenses', value: '€182,400', change: '-2.1%', trend: 'down' },
    { name: 'Net Margin', value: '24.2%', change: '+4.3%', trend: 'up' },
    { name: 'Tax Liability (Est.)', value: '€42,000', change: '+0.4%', trend: 'neutral' },
];

const monthlyData = [
    { name: 'Jan', revenue: 4000, expenses: 2400 },
    { name: 'Feb', revenue: 3000, expenses: 1398 },
    { name: 'Mar', revenue: 2000, expenses: 9800 },
    { name: 'Apr', revenue: 2780, expenses: 3908 },
    { name: 'May', revenue: 1890, expenses: 4800 },
    { name: 'Jun', revenue: 2390, expenses: 3800 },
    { name: 'Jul', revenue: 3490, expenses: 4300 },
];

const journalData = [
    { name: 'Achats', value: 45, color: '#3b82f6' }, // brand-primary
    { name: 'Ventes', value: 30, color: '#10b981' }, // emerald-500
    { name: 'Banque', value: 15, color: '#f59e0b' }, // amber-500
    { name: 'OD', value: 10, color: '#94a3b8' }, // slate-400
];

const Dashboard = () => {
    return (
        <div className="p-8 bg-slate-50 min-h-screen">
            {/* Dashboard Header */}
            <header className="flex justify-between items-end mb-8">
                <div>
                    <h1 className="text-3xl font-bold text-slate-900 tracking-tight">Financial Overview</h1>
                    <p className="text-slate-500 flex items-center gap-2 mt-1">
                        <Calendar size={14} /> Fiscal Year 2024 • Data synced 5 mins ago
                    </p>
                </div>
                <div className="flex gap-2">
                    <button className="bg-white border border-slate-200 text-slate-700 px-4 py-2 rounded-lg text-sm font-semibold hover:bg-slate-50 transition-colors">
                        Export PDF
                    </button>
                    <button className="bg-brand-primary text-white px-4 py-2 rounded-lg text-sm font-semibold shadow-lg shadow-brand-primary/20">
                        Refresh Cubes
                    </button>
                </div>
            </header>

            {/* KPI Cards */}
            <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-6 mb-8">
                {stats.map((item) => (
                    <div key={item.name} className="bg-white p-6 rounded-2xl border border-slate-200 shadow-sm">
                        <div className="flex justify-between items-start mb-4">
                            <div className="p-2 bg-slate-50 rounded-lg text-slate-400">
                                <Activity size={20} />
                            </div>
                            <span className={`text-xs font-bold px-2 py-1 rounded-full ${item.trend === 'up' ? 'bg-emerald-50 text-emerald-600' : 'bg-rose-50 text-rose-600'
                                }`}>
                                {item.change}
                            </span>
                        </div>
                        <p className="text-sm font-medium text-slate-500">{item.name}</p>
                        <p className="text-2xl font-bold text-slate-900 mt-1">{item.value}</p>
                    </div>
                ))}
            </div>

            <div className="grid grid-cols-1 lg:grid-cols-3 gap-8 mb-8">
                {/* Main Chart: P&L Trend */}
                <div className="lg:col-span-2 bg-white p-6 rounded-2xl border border-slate-200 shadow-sm">
                    <div className="flex items-center justify-between mb-6">
                        <h3 className="font-bold text-slate-900">Revenue vs. Expenses</h3>
                    </div>
                    <div className="h-80 w-full">
                        <ResponsiveContainer width="100%" height="100%">
                            <AreaChart data={monthlyData} margin={{ top: 10, right: 30, left: 0, bottom: 0 }}>
                                <defs>
                                    <linearGradient id="colorRevenue" x1="0" y1="0" x2="0" y2="1">
                                        <stop offset="5%" stopColor="#3b82f6" stopOpacity={0.8} />
                                        <stop offset="95%" stopColor="#3b82f6" stopOpacity={0} />
                                    </linearGradient>
                                    <linearGradient id="colorExpenses" x1="0" y1="0" x2="0" y2="1">
                                        <stop offset="5%" stopColor="#ef4444" stopOpacity={0.8} />
                                        <stop offset="95%" stopColor="#ef4444" stopOpacity={0} />
                                    </linearGradient>
                                </defs>
                                <XAxis dataKey="name" axisLine={false} tickLine={false} />
                                <YAxis axisLine={false} tickLine={false} />
                                <CartesianGrid vertical={false} strokeDasharray="3 3" stroke="#f1f5f9" />
                                <Tooltip />
                                <Legend verticalAlign="top" height={36} />
                                <Area type="monotone" dataKey="revenue" stroke="#3b82f6" fillOpacity={1} fill="url(#colorRevenue)" name="Revenue" />
                                <Area type="monotone" dataKey="expenses" stroke="#ef4444" fillOpacity={1} fill="url(#colorExpenses)" name="Expenses" />
                            </AreaChart>
                        </ResponsiveContainer>
                    </div>
                </div>

                {/* Circle Graph: Journal Distribution */}
                <div className="bg-white p-6 rounded-2xl border border-slate-200 shadow-sm flex flex-col">
                    <h3 className="font-bold text-slate-900 mb-6">Journal Distribution</h3>
                    <div className="flex-1 min-h-[250px] relative">
                        <ResponsiveContainer width="100%" height="100%">
                            <PieChart>
                                <Pie
                                    data={journalData}
                                    cx="50%"
                                    cy="50%"
                                    innerRadius={60}
                                    outerRadius={80}
                                    paddingAngle={5}
                                    dataKey="value"
                                >
                                    {journalData.map((entry, index) => (
                                        <Cell key={`cell-${index}`} fill={entry.color} />
                                    ))}
                                </Pie>
                                <Tooltip />
                                <Legend verticalAlign="bottom" height={36} />
                            </PieChart>
                        </ResponsiveContainer>
                        {/* Center Text Overlay */}
                        <div className="absolute inset-0 flex items-center justify-center pointer-events-none">
                            <div className="text-center">
                                <span className="text-3xl font-bold text-slate-900">100%</span>
                                <p className="text-xs text-slate-500 uppercase">Coverage</p>
                            </div>
                        </div>
                    </div>
                </div>
            </div>

            {/* Additional Stats / Scrollable Content */}
            <div className="bg-white p-6 rounded-2xl border border-slate-200 shadow-sm">
                <h3 className="font-bold text-slate-900 mb-4">Recent Transactions</h3>
                <p className="text-slate-500 mb-4">Detail view of the latest entries processed by the engine.</p>
                <div className="h-48 bg-slate-50 rounded-xl border border-dashed border-slate-200 flex items-center justify-center text-slate-400">
                    Table Placeholder (Scroll to see more)
                </div>
            </div>
        </div>
    );
};

export default Dashboard;
